require "language_pack/base"

# This file is automatically generated by rake
module LanguagePack
  class LanguagePack::Base
    CF_BUILDPACK_VERSION = "cf-v2"
    BUILDPACK_VERSION = "v116"
  end
end
