version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    open-pull-requests-limit: 1 # Limit concurrent CI runs from executing
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
