version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    open-pull-requests-limit: 1 # Limit concurrent CI runs from executing, do not remove
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
